name: Docker Build and Push (Single Repo)

on:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive' 
        fetch-depth: 0

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker info

    - name: Build Backend Docker Image
      run: docker build -t christ1113/my_stock_project:backend-latest ./stock_backend --progress=plain

    - name: Tag Backend Image
      run: docker tag christ1113/my_stock_project:backend-latest christ1113/my_stock_project:backend-v1

    - name: Push Backend Image
      run: |
        docker push christ1113/my_stock_project:backend-latest
        docker push christ1113/my_stock_project:backend-v1

  build-frontend:
    runs-on: ubuntu-22.04
    needs: build-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker info

    - name: Build Frontend Docker Image
      run: docker build -t christ1113/my_stock_project:frontend-latest ./stock_frontend --progress=plain

    - name: Tag Frontend Image
      run: docker tag christ1113/my_stock_project:frontend-latest christ1113/my_stock_project:frontend-v1

    - name: Push Frontend Image
      run: |
        docker push christ1113/my_stock_project:frontend-latest
        docker push christ1113/my_stock_project:frontend-v1
