name: Docker Build and Push (Single Repo)

on:
  push:
    branches:
      - master  # 當程式碼推送到 master 分支時觸發

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 建構後端映像
    - name: Build Backend Docker Image
      run: docker build -t christ1113/my_stock_project:backend-latest ./stock_backend

    - name: Tag Backend Image
      run: docker tag christ1113/my_stock_project:backend-latest christ1113/my_stock_project:backend-v1

    - name: Push Backend Image
      run: |
        docker push christ1113/my_stock_project:backend-latest
        docker push christ1113/my_stock_project:backend-v1

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 建構前端映像
    - name: Build Frontend Docker Image
      run: docker build -t christ1113/my_stock_project:frontend-latest ./stock_frontend

    - name: Tag Frontend Image
      run: docker tag christ1113/my_stock_project:frontend-latest christ1113/my_stock_project:frontend-v1

    - name: Push Frontend Image
      run: |
        docker push christ1113/my_stock_project:frontend-latest
        docker push christ1113/my_stock_project:frontend-v1
      
